
chassisRawData = {
  "obj": "physicalchassis1",
  "status": "ok",
  "data": {
    "Hostname": "10.100.21.7",
    "ControllerHwVersion": "2",
    "SlotCount": "12",
    "children": "powersavestats2 physicaltestmodule13 physicaltestmodule14 physicaltestmodule15 physicaltestmodule16 physicaltestmodule17 physicaltestmodule18 physicaltestmodule19 physicaltestmodule20 physicaltestmodule21 physicaltestmodule22 physicaltestmodule23 physicaltestmodule24 physicalchassistempstatus2 physicalchassisthermal8 physicalchassisthermal9 physicalchassisthermal10 physicalchassisthermal11 physicalchassisthermal12 physicalchassisthermal13 physicalchassisthermal14 physicalchassisfan7 physicalchassisfan8 physicalchassisfan9 physicalchassisfan10 physicalchassisfan11 physicalchassisfan12 physicalchassispowersupplystatus2",
    "StatusChanged": "CHASSIS_CHANGE_INIT_DONE",
    "Status": "CHASSIS_STATUS_UP",
    "DiskFree": "98538592",
    "IsConnected": "true",
    "TcpPort": "40004",
    "SyncStatus": "CHASSIS_FULL_SYNC",
    "Active": "true",
    "SyncEvent": "SYNC_EVENT_CHAIN_UPDATE",
    "IsFirmwareVersionValid": "true",
    "FirmwareVersion": "4.50.7663",
    "SerialNum": "X10500012",
    "DiskUsed": "16815008",
    "Name": "PhysicalChassis 1",
    "parent": "physicalchassismanager1",
    "ExpectedFirmwareVersion": "2.20.0000",
    "FirmwareVersionStatus": "",
    "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
    "Model": "CHASSIS_9U",
    "BackplaneHwVersion": "2",
    "FirmwareInstallProgress": "100",
    "PartNum": "SPT-11U",
    "SyncSrc": "SYNC_SRC_INTERNAL",
    "TotalDiskSize": "115353600"
  },
  "children": [
    {
      "obj": "physicaltestmodule13",
      "status": "ok",
      "data": {
        "Index": "1",
        "PortCount": "0",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "PortGroupCount": "0",
        "StatusChanged": "MODULE_CHANGE_UNKNOWN",
        "Status": "MODULE_STATUS_UNKNOWN",
        "PortGroupSize": "0",
        "Description": "",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "HwRevCode": "",
        "SyncStatus": "MODULE_OUT_OF_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "true",
        "FirmwareVersion": "",
        "SerialNum": "",
        "AvailableProfileDescriptions": "",
        "TestPackages": "",
        "Name": "PhysicalTestModule 25",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "",
        "FirmwareVersionStatus": "",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "",
        "SupportedPortGroupSizes": "",
        "ProductId": "",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "",
        "FirmwareInstallProgress": "0",
        "ProductFamily": "",
        "PartNum": "",
        "TotalDiskSize": "0"
      }
    },
    {
      "obj": "physicaltestmodule14",
      "status": "ok",
      "data": {
        "Index": "2",
        "PortCount": "2",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "children": "physicalportgroup34",
        "StatusChanged": "MODULE_CHANGE_INIT_DONE",
        "Status": "MODULE_STATUS_UP",
        "PortGroupSize": "2",
        "Description": "2 PORT 10/100/1000 Dual Media Rev B",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "PortGroupCount": "1",
        "HwRevCode": "C6",
        "SyncStatus": "MODULE_IN_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "false",
        "FirmwareVersion": "4.50.7663",
        "SerialNum": "M06020494",
        "AvailableProfileDescriptions": "",
        "TestPackages": "l4l7-4.50.1216 stc-4.50.7663",
        "Name": "PhysicalTestModule 26",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "4.40.3456",
        "FirmwareVersionStatus": "The current test module firmware with version 4.50.7663 is not supported. Please upgrade the test module firmware to version 4.40.3456.",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "EDM-2002B",
        "SupportedPortGroupSizes": "2",
        "ProductId": "80-000025",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "l2l3 stc stc_vtc stc_pentium4 l4l7",
        "FirmwareInstallProgress": "0",
        "testmodulecapabilitiesrelation-Sources": "testmodulecapabilities4",
        "ProductFamily": "RAVEN",
        "PartNum": "EDM-2002B",
        "TotalDiskSize": "0"
      },
      "children": [
        {
          "obj": "physicalportgroup34",
          "status": "ok",
          "data": {
            "Index": "1",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport67 physicalport68",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "128",
            "PortsCsvString": "1,2",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 87",
            "parent": "physicaltestmodule14",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "2"
          }
        }
      ]
    },
    {
      "obj": "physicaltestmodule15",
      "status": "ok",
      "data": {
        "Index": "3",
        "PortCount": "4",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "children": "physicalportgroup35 physicalportgroup36",
        "StatusChanged": "MODULE_CHANGE_INIT_DONE",
        "Status": "MODULE_STATUS_UP",
        "PortGroupSize": "2",
        "Description": "HYPERMETRICS CM 10/100/1000 DUAL MEDIA 4-PORTS",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "PortGroupCount": "2",
        "HwRevCode": "A8",
        "SyncStatus": "MODULE_IN_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "false",
        "FirmwareVersion": "4.50.7663",
        "SerialNum": "E08470636",
        "AvailableProfileDescriptions": "",
        "TestPackages": "l4l7-4.50.1216 stc-4.50.7663",
        "Name": "PhysicalTestModule 27",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "4.40.3456",
        "FirmwareVersionStatus": "The current test module firmware with version 4.50.7663 is not supported. Please upgrade the test module firmware to version 4.40.3456.",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "EDM-3001A",
        "SupportedPortGroupSizes": "1 2",
        "ProductId": "80-001403",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "l2l3 stc stc_vtc stc_pentium4 l4l7",
        "FirmwareInstallProgress": "0",
        "testmodulecapabilitiesrelation-Sources": "testmodulecapabilities3",
        "ProductFamily": "SHADOWCAT",
        "PartNum": "EDM-3001A",
        "TotalDiskSize": "0"
      },
      "children": [
        {
          "obj": "physicalportgroup35",
          "status": "ok",
          "data": {
            "Index": "1",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "6",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport71 physicalport72",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "2048",
            "PortsCsvString": "1,2",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 77",
            "parent": "physicaltestmodule15",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "2"
          }
        },
        {
          "obj": "physicalportgroup36",
          "status": "ok",
          "data": {
            "Index": "2",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "6",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport69 physicalport70",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "2048",
            "PortsCsvString": "3,4",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 78",
            "parent": "physicaltestmodule15",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "2"
          }
        }
      ]
    },
    {
      "obj": "physicaltestmodule16",
      "status": "ok",
      "data": {
        "Index": "4",
        "PortCount": "0",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "PortGroupCount": "0",
        "StatusChanged": "MODULE_CHANGE_UNKNOWN",
        "Status": "MODULE_STATUS_UNKNOWN",
        "PortGroupSize": "0",
        "Description": "",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "HwRevCode": "",
        "SyncStatus": "MODULE_OUT_OF_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "true",
        "FirmwareVersion": "",
        "SerialNum": "",
        "AvailableProfileDescriptions": "",
        "TestPackages": "",
        "Name": "PhysicalTestModule 28",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "",
        "FirmwareVersionStatus": "",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "",
        "SupportedPortGroupSizes": "",
        "ProductId": "",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "",
        "FirmwareInstallProgress": "0",
        "ProductFamily": "",
        "PartNum": "",
        "TotalDiskSize": "0"
      }
    },
    {
      "obj": "physicaltestmodule17",
      "status": "ok",
      "data": {
        "Index": "5",
        "PortCount": "8",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "children": "physicalportgroup47 physicalportgroup48 physicalportgroup49 physicalportgroup50 physicalportgroup51 physicalportgroup52 physicalportgroup53 physicalportgroup54",
        "StatusChanged": "MODULE_CHANGE_INIT_DONE",
        "Status": "MODULE_STATUS_UP",
        "PortGroupSize": "1",
        "Description": "HYPERMETRICS CV 10G SFP+ 8-PORTS",
        "IsPortGroupRebootSupported": "false",
        "DiskFree": "0",
        "PortGroupCount": "8",
        "HwRevCode": "A7",
        "SyncStatus": "MODULE_IN_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "false",
        "FirmwareVersion": "4.50.7663",
        "SerialNum": "E08520353",
        "AvailableProfileDescriptions": "",
        "TestPackages": "stc-4.50.7663",
        "Name": "PhysicalTestModule 29",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "4.40.3456",
        "FirmwareVersionStatus": "The current test module firmware with version 4.50.7663 is not supported. Please upgrade the test module firmware to version 4.40.3456.",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "CV-10G-S8",
        "SupportedPortGroupSizes": "1",
        "ProductId": "80-001562",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "l2l3 stc stc_vtc stc_pentium4",
        "FirmwareInstallProgress": "0",
        "testmodulecapabilitiesrelation-Sources": "testmodulecapabilities1",
        "ProductFamily": "PYRO",
        "PartNum": "CV-10G-S8",
        "TotalDiskSize": "0"
      },
      "children": [
        {
          "obj": "physicalportgroup47",
          "status": "ok",
          "data": {
            "Index": "1",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport73",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "1",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 79",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup48",
          "status": "ok",
          "data": {
            "Index": "2",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport75",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "2",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 80",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup49",
          "status": "ok",
          "data": {
            "Index": "3",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport74",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "3",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 81",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup50",
          "status": "ok",
          "data": {
            "Index": "4",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport77",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "4",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 82",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup51",
          "status": "ok",
          "data": {
            "Index": "5",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport76",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "5",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 83",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup52",
          "status": "ok",
          "data": {
            "Index": "6",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport79",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "6",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 84",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup53",
          "status": "ok",
          "data": {
            "Index": "7",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport80",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "7",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 85",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup54",
          "status": "ok",
          "data": {
            "Index": "8",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport81",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "8",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 86",
            "parent": "physicaltestmodule17",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        }
      ]
    },
    {
      "obj": "physicaltestmodule18",
      "status": "ok",
      "data": {
        "Index": "6",
        "PortCount": "8",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "STC Functional Profile",
        "children": "physicalportgroup39 physicalportgroup40 physicalportgroup41 physicalportgroup42 physicalportgroup43 physicalportgroup44 physicalportgroup45 physicalportgroup46",
        "StatusChanged": "MODULE_CHANGE_INIT_DONE",
        "Status": "MODULE_STATUS_UP",
        "PortGroupSize": "1",
        "Description": "HYPERMETRICS MX 10G SFP+ 8-PORTS",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "PortGroupCount": "8",
        "HwRevCode": "A2",
        "SyncStatus": "MODULE_IN_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "false",
        "FirmwareVersion": "4.50.7663",
        "SerialNum": "E11050262",
        "AvailableProfileDescriptions": "{STU Functional Profile} {L4L7-Performance Profile} {STC Functional Profile} {STC 1x4 Port LAG Functional Profile} {STC 1x8 Port LAG Functional Profile} {L4L7 Functional Profile} {STC 2x2 Port LAG Functional Profile} {STC 2x4 Port LAG Functional Profile} {STC 4x2 Port LAG Functional Profile}",
        "TestPackages": "stc-4.50.7663 l4l7Vm-4.50.1216",
        "Name": "PhysicalTestModule 30",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "4.40.3456",
        "FirmwareVersionStatus": "The current test module firmware with version 4.50.7663 is not supported. Please upgrade the test module firmware to version 4.40.3456.",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "MX-10G-S8",
        "SupportedPortGroupSizes": "1",
        "ProductId": "80-000950",
        "ActiveProfile": "Default",
        "AvailableProfiles": "STU-Functional L4L7-Performance Default STC-1x4-Port-LAG-Functional STC-1x8-Port-LAG-Functional L4L7-Functional STC-2x2-Port-LAG-Functional STC-2x4-Port-LAG-Functional STC-4x2-Port-LAG-Functional",
        "SupportedTestPackages": "l2l3 stc l4l7Vm lsVm studioVm k9",
        "FirmwareInstallProgress": "0",
        "testmodulecapabilitiesrelation-Sources": "testmodulecapabilities5",
        "ProductFamily": "BLINK",
        "PartNum": "MX-10G-S8",
        "TotalDiskSize": "0"
      },
      "children": [
        {
          "obj": "physicalportgroup39",
          "status": "ok",
          "data": {
            "Index": "1",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport78",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "1",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 67",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup40",
          "status": "ok",
          "data": {
            "Index": "2",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport85",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "2",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 68",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup41",
          "status": "ok",
          "data": {
            "Index": "3",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport82",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "3",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 69",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup42",
          "status": "ok",
          "data": {
            "Index": "4",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport84",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "4",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 70",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup43",
          "status": "ok",
          "data": {
            "Index": "5",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport83",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "5",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 71",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup44",
          "status": "ok",
          "data": {
            "Index": "6",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport88",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "6",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 72",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup45",
          "status": "ok",
          "data": {
            "Index": "7",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport87",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "7",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 73",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup46",
          "status": "ok",
          "data": {
            "Index": "8",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "2",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport86",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "1738",
            "PortsCsvString": "8",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 74",
            "parent": "physicaltestmodule18",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        }
      ]
    },
    {
      "obj": "physicaltestmodule19",
      "status": "ok",
      "data": {
        "Index": "7",
        "PortCount": "4",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "children": "physicalportgroup37 physicalportgroup38",
        "StatusChanged": "MODULE_CHANGE_INIT_DONE",
        "Status": "MODULE_STATUS_UP",
        "PortGroupSize": "2",
        "Description": "HYPERMETRICS CM 10/100/1000 DUAL MEDIA 4-PORTS",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "PortGroupCount": "2",
        "HwRevCode": "A23",
        "SyncStatus": "MODULE_IN_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "false",
        "FirmwareVersion": "4.50.7663",
        "SerialNum": "E09120511",
        "AvailableProfileDescriptions": "",
        "TestPackages": "l4l7-4.50.1216 stc-4.50.7663",
        "Name": "PhysicalTestModule 31",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "4.40.3456",
        "FirmwareVersionStatus": "The current test module firmware with version 4.50.7663 is not supported. Please upgrade the test module firmware to version 4.40.3456.",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "CM-1G-D4",
        "SupportedPortGroupSizes": "1 2",
        "ProductId": "80-001403",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "l2l3 stc stc_vtc stc_pentium4 l4l7",
        "FirmwareInstallProgress": "0",
        "testmodulecapabilitiesrelation-Sources": "testmodulecapabilities2",
        "ProductFamily": "SHADOWCAT",
        "PartNum": "CM-1G-D4",
        "TotalDiskSize": "0"
      },
      "children": [
        {
          "obj": "physicalportgroup37",
          "status": "ok",
          "data": {
            "Index": "1",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "6",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport89 physicalport90",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "2048",
            "PortsCsvString": "1,2",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 75",
            "parent": "physicaltestmodule19",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "2"
          }
        },
        {
          "obj": "physicalportgroup38",
          "status": "ok",
          "data": {
            "Index": "2",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "6",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport92 physicalport93",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "2048",
            "PortsCsvString": "3,4",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 76",
            "parent": "physicaltestmodule19",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "2"
          }
        }
      ]
    },
    {
      "obj": "physicaltestmodule20",
      "status": "ok",
      "data": {
        "Index": "8",
        "PortCount": "8",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "children": "physicalportgroup55 physicalportgroup56 physicalportgroup57 physicalportgroup58 physicalportgroup59 physicalportgroup60 physicalportgroup61 physicalportgroup62",
        "StatusChanged": "MODULE_CHANGE_INIT_DONE",
        "Status": "MODULE_STATUS_UP",
        "PortGroupSize": "1",
        "Description": "HYPERMETRICS CV 10G SFP+ 8-PORTS",
        "IsPortGroupRebootSupported": "false",
        "DiskFree": "0",
        "PortGroupCount": "8",
        "HwRevCode": "A17",
        "SyncStatus": "MODULE_IN_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "false",
        "FirmwareVersion": "4.50.7663",
        "SerialNum": "E09160108",
        "AvailableProfileDescriptions": "",
        "TestPackages": "stc-4.50.7663",
        "Name": "PhysicalTestModule 32",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "4.40.3456",
        "FirmwareVersionStatus": "The current test module firmware with version 4.50.7663 is not supported. Please upgrade the test module firmware to version 4.40.3456.",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "CV-10G-S8",
        "SupportedPortGroupSizes": "1",
        "ProductId": "80-001562",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "l2l3 stc stc_vtc stc_pentium4",
        "FirmwareInstallProgress": "0",
        "testmodulecapabilitiesrelation-Sources": "testmodulecapabilities1",
        "ProductFamily": "PYRO",
        "PartNum": "CV-10G-S8",
        "TotalDiskSize": "0"
      },
      "children": [
        {
          "obj": "physicalportgroup55",
          "status": "ok",
          "data": {
            "Index": "1",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport91",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "1",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 59",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup56",
          "status": "ok",
          "data": {
            "Index": "2",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport94",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "2",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 60",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup57",
          "status": "ok",
          "data": {
            "Index": "3",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport99",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "3",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 61",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup58",
          "status": "ok",
          "data": {
            "Index": "4",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport95",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "4",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 62",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup59",
          "status": "ok",
          "data": {
            "Index": "5",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport97",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "5",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 63",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup60",
          "status": "ok",
          "data": {
            "Index": "6",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport96",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "6",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 64",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup61",
          "status": "ok",
          "data": {
            "Index": "7",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport98",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "7",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 65",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        },
        {
          "obj": "physicalportgroup62",
          "status": "ok",
          "data": {
            "Index": "8",
            "OwnershipState": "OWNERSHIP_STATE_AVAILABLE",
            "CpuCores": "1",
            "OwnerAccessLevel": "ACCESS_LEVEL_VIEW",
            "OwnerUserId": "",
            "children": "physicalport100",
            "TestPackageVersionStatus": "The current test package: stc with version 4.50.7663 is not supported. Please upgrade the test package: stc to version 4.40.3456.",
            "StatusChanged": "MODULE_CHANGE_INIT_DONE",
            "Status": "MODULE_STATUS_UP",
            "TotalMemoryInMb": "512",
            "PortsCsvString": "8",
            "TestPackageVersion": "4.50.7663",
            "SyncStatus": "MODULE_IN_SYNC",
            "IsTestPackageVersionValid": "false",
            "Active": "true",
            "OwnerTimestamp": "",
            "TestPackage": "stc",
            "Name": "PhysicalPortGroup 66",
            "parent": "physicaltestmodule20",
            "ExpectedTestPackageVersion": "4.40.3456",
            "Enabled": "true",
            "OwnerProcessId": "",
            "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
            "OwnerHostname": "",
            "ReservedByUser": "false",
            "FirmwareInstallProgress": "0",
            "Size": "1"
          }
        }
      ]
    },
    {
      "obj": "physicaltestmodule21",
      "status": "ok",
      "data": {
        "Index": "9",
        "PortCount": "0",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "PortGroupCount": "0",
        "StatusChanged": "MODULE_CHANGE_UNKNOWN",
        "Status": "MODULE_STATUS_UNKNOWN",
        "PortGroupSize": "0",
        "Description": "",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "HwRevCode": "",
        "SyncStatus": "MODULE_OUT_OF_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "true",
        "FirmwareVersion": "",
        "SerialNum": "",
        "AvailableProfileDescriptions": "",
        "TestPackages": "",
        "Name": "PhysicalTestModule 33",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "",
        "FirmwareVersionStatus": "",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "",
        "SupportedPortGroupSizes": "",
        "ProductId": "",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "",
        "FirmwareInstallProgress": "0",
        "ProductFamily": "",
        "PartNum": "",
        "TotalDiskSize": "0"
      }
    },
    {
      "obj": "physicaltestmodule22",
      "status": "ok",
      "data": {
        "Index": "10",
        "PortCount": "0",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "PortGroupCount": "0",
        "StatusChanged": "MODULE_CHANGE_UNKNOWN",
        "Status": "MODULE_STATUS_UNKNOWN",
        "PortGroupSize": "0",
        "Description": "",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "HwRevCode": "",
        "SyncStatus": "MODULE_OUT_OF_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "true",
        "FirmwareVersion": "",
        "SerialNum": "",
        "AvailableProfileDescriptions": "",
        "TestPackages": "",
        "Name": "PhysicalTestModule 34",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "",
        "FirmwareVersionStatus": "",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "",
        "SupportedPortGroupSizes": "",
        "ProductId": "",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "",
        "FirmwareInstallProgress": "0",
        "ProductFamily": "",
        "PartNum": "",
        "TotalDiskSize": "0"
      }
    },
    {
      "obj": "physicaltestmodule23",
      "status": "ok",
      "data": {
        "Index": "11",
        "PortCount": "0",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "PortGroupCount": "0",
        "StatusChanged": "MODULE_CHANGE_UNKNOWN",
        "Status": "MODULE_STATUS_UNKNOWN",
        "PortGroupSize": "0",
        "Description": "",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "HwRevCode": "",
        "SyncStatus": "MODULE_OUT_OF_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "true",
        "FirmwareVersion": "",
        "SerialNum": "",
        "AvailableProfileDescriptions": "",
        "TestPackages": "",
        "Name": "PhysicalTestModule 35",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "",
        "FirmwareVersionStatus": "",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "",
        "SupportedPortGroupSizes": "",
        "ProductId": "",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "",
        "FirmwareInstallProgress": "0",
        "ProductFamily": "",
        "PartNum": "",
        "TotalDiskSize": "0"
      }
    },
    {
      "obj": "physicaltestmodule24",
      "status": "ok",
      "data": {
        "Index": "12",
        "PortCount": "0",
        "IsTestModuleRebootSupported": "true",
        "ActiveProfileDescription": "Default Profile",
        "PortGroupCount": "0",
        "StatusChanged": "MODULE_CHANGE_UNKNOWN",
        "Status": "MODULE_STATUS_UNKNOWN",
        "PortGroupSize": "0",
        "Description": "",
        "IsPortGroupRebootSupported": "true",
        "DiskFree": "0",
        "HwRevCode": "",
        "SyncStatus": "MODULE_OUT_OF_SYNC",
        "Active": "true",
        "IsFirmwareVersionValid": "true",
        "FirmwareVersion": "",
        "SerialNum": "",
        "AvailableProfileDescriptions": "",
        "TestPackages": "",
        "Name": "PhysicalTestModule 36",
        "parent": "physicalchassis1",
        "DiskUsed": "0",
        "ExpectedFirmwareVersion": "",
        "FirmwareVersionStatus": "",
        "FirmwareInstallStatus": "FIRMWARE_INSTALL_INACTIVE",
        "Model": "",
        "SupportedPortGroupSizes": "",
        "ProductId": "",
        "ActiveProfile": "Default",
        "AvailableProfiles": "",
        "SupportedTestPackages": "",
        "FirmwareInstallProgress": "0",
        "ProductFamily": "",
        "PartNum": "",
        "TotalDiskSize": "0"
      }
    }
  ]
}

###
class ChassisInfo
    constructor: (data) ->
        @partnum = data.PartNum
        @hostname = data.Hostname
        @slotcount = data.SlotCount
        @serialnumber = data.SerialNum
        @fwversion = data.FirmwareVersion
        @modules = []

    GetData: ->
        data = {
            'description' : @partnum
            'ip' : @hostname
            'firmware' : @fwversion
            'total_slots' : @slotcount
            'serial_number' : @serialnumber
        }
        return data

class SlotInfo
    constructor: (data) ->
        @index = data.Index
        @fwversion = data.FirmwareVersion
        @cpu = 0
        @mode = "NA"
        @serialnum = data.SerialNum
        @model = data.Model
        @profile = data.ActiveProfile
        @portgroups = []

    GetData: ->
        data = {
            'id' : @index
            "software": @fwversion
            "cpu": @cpu
            "mode": @mode
            "serial_number": @serialnum
            'model' : @model
            "profile": @profile
        }
        return data

class PortGroupInfo
    constructor: (data) ->
        @index = data.Index
        @reserved = data.OwnershipState
        @cpucores = data.CpuCores
        @memoryinkb = data.TotalMemoryInMb * 1000
        @pacakgeversion = data.TestPackage + data.TestPackageVersion
    GetData: ->
        data = {
            'id' : @index
            'reserved' : @reserved
            "cores": @cpucores
            "memory": @memoryinkb
            "software": @pacakgeversion
            "capacity": 10
        }
        return data
###

ChassisInfo = require './ChassisInfo'
SlotInfo = require './SlotInfo'
PortGroupInfo = require './PortGroupInfo'

console.log("Starting script")

chassisInfo = new ChassisInfo(chassisRawData.data)

for module in chassisRawData.children
    #skip if module does not have any ports
    if not module.children
        continue
    moduleInfo = new SlotInfo(module.data)

    for pg in module.children
        pgInfo = new PortGroupInfo(pg.data)       
        moduleInfo.Portgroups.push(pgInfo)

    chassisInfo.Modules.push(moduleInfo)


chassisdata = chassisInfo.Get_Data()

chassisdata['slots'] = []
for module in chassisInfo.Modules
    moduledata = module.Get_Data()
    moduledata['port_groups'] = []
    for pgInfo in module.Portgroups
        pgdata = pgInfo.Get_Data()
        moduledata.port_groups.push(pgdata)
    chassisdata.slots.push(moduledata)


conv_data = JSON.stringify(chassisdata)
console.log("converted data")
console.log(conv_data)

#console.log(JSON.stringify(chassisRawData))
###
convertdata = {}

#chassis data
convertdata['description'] = chassisRawData.data.PartNum
convertdata['ip'] = chassisRawData.data.Hostname
convertdata['total_slots'] = chassisRawData.data.SlotCount
convertdata['serial_number'] = chassisRawData.SerialNum

convertdata['slots'] = []

for module in chassisRawData.children
    #skip if module does not have any ports
    if not module.children
        continue
    slotdata = {}
    slotdata['id'] = module.data.Index
    slotdata['model'] = module.data.Model
    slotdata['port_groups'] = []

    for pg in module.children
        pgdata = {}
        pgdata['id'] = pg.data.Index
        pgdata['reserved'] = pg.data.OwnershipState

        slotdata.port_groups.push(pgdata)

    convertdata.slots.push(slotdata)

conv_data = JSON.stringify(convertdata)
console.log("converted data")
console.log(conv_data)
###


